<?php
/**
 * 
 * 
 * 
 * 
 * 
 * 
 */

foreach (glob("Controller/*.php") as $filename)
{
	include $filename;
}

define('PROJECT_DIR', __DIR__);

$serial = '16999';
$provider = 'TEST';
$type = 'organisation';
$description = 'descriptions ....';
$personnel = 'W.L.Pang';
$signature = 'W.L.Pang';
$additional_info = 'Generated by scripting';


$router = new Router();
$router -> start();